services:
  - type: web
    name: doohoon-linebot
    env: docker
    plan: free
    branch: main
    rootDir: .
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 10000
